---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: dynalite
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: dynalite
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: fpm
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: fpm
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: http-echo-test
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: kinesalite
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: kinesalite
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: localstripe
    schedule:
      interval: daily
